# .streamlit/secrets.toml

dialect = "postgresql"
DB_HOST = "dpg-cupmsjin91rc73an5o3g-a.oregon-postgres.render.com"
DB_PORT = "5432"
DB_NAME = "db_futsal_minas"
DB_USER = "minas_futsal"
DB_PASSWORD = "VmLXuiQ9mzkxxQVAD9N1LLJp9nYIiWu2"